# 공통
spring:
  output:
    ansi:
      enabled: always
  application:
    name: goNyangBack
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_BUCKET}
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  redirect-uri: ${NAVER_REDIRECT_URI}
  auth-uri: https://nid.naver.com/oauth2.0/authorize
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me
google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}
logging:
  file:
    path: ./logs




# security 관련
secret-key: ${JWT_SECRET_KEY}
access-expiration-hours: 6
refresh-expiration-hours: 240

--- # 운영
spring:
  config:
    activate:
      on-profile: product
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIA_HOST:maria-db}:${MARIA_PORT:3306}/goNyangProject?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  file:
    storage:
      path: ${FILE_STORAGE_PATH:/uploads/}
  app:
    frontend:
      login-success-uri: ${APP_FRONTEND_LOGIN_SUCCESS_URI}
      login-fail-uri: ${APP_FRONTEND_LOGIN_FAIL_URI}
logging:
  level:
    root: info

--- # 로컬
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://${MARIA_HOST:localhost}:${MARIA_PORT:3306}/goNyangProject?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  file:
    storage:
      path: C:/GoNyangService/uploads/
  app:
    frontend:
      login-success-uri: http://localhost:3000
      login-fail-uri: http://localhost:3000/member/login
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_BUCKET}

logging:
  level:
    root: info