# 공통
spring:
  output:
    ansi:
      enabled: always
  application:
    name: tossBack
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  redirect-uri: ${NAVER_REDIRECT_URI}
  auth-uri: https://nid.naver.com/oauth2.0/authorize
  token-uri: https://nid.naver.com/oauth2.0/token
  user-info-uri: https://openapi.naver.com/v1/nid/me
google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}
logging:
  file:
    path: ./logs




# security 관련
secret-key: 33D3AFA30260B16223DB5995202F35B1AFDB14B2FB8AE60D7CF79CD402F52D0769742896041858C6C9D632E2346E48CC98ECDE7B2E31B1F8624C223B6BFC15DD
access-expiration-hours: 6
refresh-expiration-hours: 240

--- # 운영
spring:
  config:
    activate:
      on-profile: product
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MARIA_HOST:maria-db}:${MARIA_PORT:3306}/goNyangProject?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: WB12345!@
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
logging:
  level:
    root: info

--- # 로컬
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://${MARIA_HOST:localhost}:${MARIA_PORT:3306}/goNyangProject?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: WB12345!@
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  file:
    storage:
      path: ./uploads/pets
logging:
  level:
    root: info
